name: Lint and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ember-try-scenario: [ember-default, ember-lts-3.4, ember-lts-3.8, ember-release, ember-beta, ember-canary]

    steps:
    - uses: actions/checkout@v1
    - name: Install, Lint and Test
      run: |
        yarn install
        yarn lint:js
        yarn ember try:one ${{ matrix.ember-try-scenario }}
      env:
        CI: true
