name: Lint and Test

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - run: yarn lint:js -f tap

  test:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        ember-try-scenario: [ember-default, ember-lts-3.4, ember-lts-3.8, ember-release, ember-beta, ember-canary]
    steps:
    - run: yarn ember try:one ${{ matrix.ember-try-scenario }}
      env:
        CI: true
